import os

# API Configuration
ROBOFLOW_API_KEY = "ROBOFLOW_API_KEY"
FACE_DETECTION_MODEL = "face-detection-mik1i-tocjc/2"
SERPAPI_API_KEY = "SERPAPI_API_KEY"
IMGBB_API_KEY = "IMGBB_API_KEY"
SCRAPFLY_API_KEY = "SCRAPFLY_API_KEY"
OPENAI_API_KEY = "OPENAI_API_KEY"

# Video configuration
FRAME_WIDTH = 640
FRAME_HEIGHT = 480 
